# Generated by Django 4.1.1 on 2022-09-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sID', models.IntegerField()),
                ('sName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subName', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sApply', models.CharField(max_length=10)),
                ('subID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectID', to='subjects.subject')),
            ],
        ),
    ]
