# Generated by Django 4.2.6 on 2023-10-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
